{% set name = "aimodelshare" %}
{% set version = "0.0.164" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0404aa94bf37ecd0040f2a20de24e469441607ba41ddd5c31bea33de5ccf969f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - absl-py
    - astunparse ==1.6.3
    - boto3 ==1.18.2
    - botocore ==1.21.2
    - dill
    - docker-py >=5.0.0
    - ipython
    - importlib-resources
    - jinja2
    - keras2onnx >=1.7.0
    - networkx ==2.6.3
    - onnx >=1.9.0
    - onnxconverter-common >=1.7.0
    - onnxmltools >=1.6.1
    - onnxruntime >=1.7.0
    - pathlib >=1.0.1
    - psutil >=5.9.1
    - pydot >=1.3.0
    - pyjwt ==2.4.0
    - pympler ==0.9
    - python >=3.7
    - python-wget ==3.2
    - pytorch >=1.8.1
    - regex
    - requests
    - scikit-learn ==0.24.2
    - seaborn >=0.11.2
    - shortuuid >=1.0.8
    - skl2onnx >=1.8.0
    - tensorflow >=2.5.0
    - tf2onnx
    - urllib3 ==1.25.11
    - xgboost >=0.90

test:
  imports:
    - aimodelshare
    - aimodelshare.custom_approach
    - aimodelshare.main
    - aimodelshare.sam

about:
  home: https://www.modelshare.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Deploy locally saved machine learning models to a live rest API and web-dashboard.  Share it with the world via modelshare.org
  doc_url: https://github.com/AIModelShare/aimodelshare/blob/master/README.md
  dev_url: https://github.com/AIModelShare/aimodelshare

extra:
  recipe-maintainers:
    - VijayKalmath
    - raudipra
    - mikedparrott
